import type { Mitigators } from "./schema";

/**
 * Certified radon mitigators, baked as typed data (the only seam is
 * `lib/content.ts`). California roster from the CDPH "Certified Mitigators"
 * list (`cdph_mitigators`); office location + phone enriched from the CA Contractors
 * State License Board (`cslb`); lat/lng geocoded once via the US Census Geocoder
 * (street-level) with an OSM city/ZIP fallback for PO-box-only addresses
 * (`precise: false`). Regenerate with `scripts/geocode-mitigators.mjs`.
 *
 * Snapshot date in `updatedAt`; CDPH notes the list is not updated daily.
 * `certId` is the de-dupe key (the source list can repeat a person).
 */
export const MITIGATORS = {
  updatedAt: "2026-06-15",
  copy: {
    title: "Find a California-Certified Mitigator",
    description:
      "California-certified radon mitigation contractors with phone numbers, from the CDPH certified list and the state license board.",
    heading: "Find a California-certified radon mitigator",
    intro:
      "If a test comes back at or above 4 pCi/L, the next step is hiring a certified mitigator. California regulates the work itself: a mitigator must hold a national certification and a California contractor license, and be on the CDPH certified list. Everyone below clears that bar, so they can legally mitigate a California home, South Lake Tahoe included.",
    mapNote:
      "Pins mark each contractor's office, not their service area or where they're licensed. A few are based in Nevada but certified for California. Call to confirm they cover your area.",
    mapAriaLabel: "Map of certified radon mitigators",
    list: {
      ariaLabel: "Certified radon mitigators in California",
      caption:
        "Listed where each business is based. Many serve a wider area, so call to confirm they cover your county.",
      updatedLabel: "Updated",
      headers: { name: "Name", location: "Location", phone: "Phone" },
      servesCaveat: "serves California",
    },
  },
  mitigators: [
    {
      name: "Scott Cole",
      business: "Advanced Construction Technologies LLC",
      certId: "115293",
      city: "Irvine",
      state: "CA",
      zip: "92618",
      phone: "(949) 502-5355",
      caLicense: "797379",
      lat: 33.64013,
      lng: -117.74044,
      precise: true,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Norman Denny",
      business: "College City Construction",
      certId: "106142",
      city: "Minden",
      state: "NV",
      zip: "89423",
      phone: "(775) 691-7101",
      caLicense: "241944",
      lat: 38.9533,
      lng: -119.76366,
      precise: false,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Cameron Dopke",
      business: "Environmental Inspections & Construction Inc",
      certId: "112346",
      city: "Markleeville",
      state: "CA",
      zip: "96120",
      phone: "(530) 544-1862",
      caLicense: "922311",
      lat: 38.801,
      lng: -119.80097,
      precise: true,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Fred Ellrott",
      certId: "101023",
      city: "Somis",
      state: "CA",
      zip: "93066",
      phone: "(805) 732-2476",
      caLicense: "617021",
      lat: 34.25723,
      lng: -118.99621,
      precise: false,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Daniel Frayman",
      business: "Prosirv Inc",
      certId: "114455",
      city: "Woodland Hills",
      state: "CA",
      zip: "91367",
      phone: "(818) 616-7776",
      caLicense: "1071369",
      lat: 34.16836,
      lng: -118.61934,
      precise: true,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Jason Gregory",
      business: "Jason Gregory Inc",
      certId: "107970",
      city: "Thousand Oaks",
      state: "CA",
      zip: "91360",
      phone: "(805) 432-0042",
      caLicense: "843797",
      lat: 34.21779,
      lng: -118.87031,
      precise: true,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Jordan Heichman",
      certId: "106156",
      city: "Placerville",
      state: "CA",
      zip: "95667",
      phone: "(530) 621-4052",
      caLicense: "816271",
      lat: 38.69573,
      lng: -120.76734,
      precise: true,
      sourceId: "cdph_mitigators",
    },
    {
      name: "John Henderson",
      business: "Apex Building & Restoration Inc",
      certId: "108871",
      city: "Santa Barbara",
      state: "CA",
      zip: "93105",
      phone: "(805) 280-6616",
      caLicense: "632908",
      lat: 34.44035,
      lng: -119.73846,
      precise: true,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Eddie Huchingson",
      business: "Radon Solutions California LLC",
      certId: "107621",
      city: "Thousand Oaks",
      state: "CA",
      zip: "91360",
      phone: "(805) 908-9274",
      caLicense: "612436",
      lat: 34.2053,
      lng: -118.86304,
      precise: true,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Peter Mandel",
      business: "MG Remediation Inc",
      certId: "104696",
      city: "San Leandro",
      state: "CA",
      zip: "94577",
      phone: "(510) 293-3009",
      caLicense: "839709",
      lat: 37.71752,
      lng: -122.15988,
      precise: true,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Edward Riley",
      business: "Tahoe Mold and Water Inc",
      certId: "106415",
      city: "Tahoe City",
      state: "CA",
      zip: "96145",
      phone: "(530) 581-1094",
      caLicense: "960994",
      lat: 39.16894,
      lng: -120.14348,
      precise: false,
      sourceId: "cdph_mitigators",
    },
    {
      name: "Iurii Zharkov",
      business: "A1 Construction and Restoration Inc",
      certId: "115915",
      city: "Beverly Hills",
      state: "CA",
      zip: "90212",
      phone: "(951) 712-4722",
      caLicense: "1118941",
      lat: 34.06107,
      lng: -118.40024,
      precise: true,
      sourceId: "cdph_mitigators",
    },
  ],
} satisfies Mitigators;
